language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -q
  - sudo apt-get install -y g++-5 libboost-system1.55-dev
  - export CXX=g++-5
  - export CC=gcc-5
script: cmake . && make
